import { useEffect, useMemo, useState } from "react";
import { buildPromptContext } from "../lib/prompt-context";
import { createTasteProfile, parseProfiles, parseProjects, PROFILE_STORAGE_KEY, PROJECT_STORAGE_KEY, recoverProject, serializeProfiles, type ProjectMemory, type TasteProfile } from "../lib/taste-profiles";
import styles from "./styles/research-workspace.module.scss";

const blankProject = (): ProjectMemory => recoverProject({ title: "New creative project", instructions: "", signals: [] }, []);
const fields: Array<[keyof TasteProfile, string, string]> = [["visualStyle", "Visual style / mood", "e.g. tactile editorial, optimistic"], ["composition", "Composition / camera", "e.g. asymmetrical close crops"], ["colorLighting", "Color / lighting", "e.g. warm daylight, muted green"], ["brandVoice", "Brand voice", "e.g. direct, curious, grounded"], ["audience", "Audience", "Who this is for"], ["constraints", "Recurring constraints", "e.g. no text overlays"], ["avoid", "Avoid", "e.g. glossy stock-photo poses"], ["guidance", "Additional guidance", "Optional notes"]];

export default function ResearchWorkspace() {
  const [profiles, setProfiles] = useState<TasteProfile[]>([]); const [project, setProject] = useState<ProjectMemory>(blankProject());
  const [draft, setDraft] = useState<TasteProfile | null>(null); const [ready, setReady] = useState(false); const [signal, setSignal] = useState(""); const [result, setResult] = useState<{ id: string; influence: ReturnType<typeof buildPromptContext>["influence"] } | null>(null);
  useEffect(() => { queueMicrotask(() => { const loaded = parseProfiles(localStorage.getItem(PROFILE_STORAGE_KEY)); setProfiles(loaded); const projects = parseProjects(localStorage.getItem(PROJECT_STORAGE_KEY), loaded); setProject(projects[0] || blankProject()); setReady(true); }); }, []);
  useEffect(() => { if (ready) localStorage.setItem(PROFILE_STORAGE_KEY, serializeProfiles(profiles)); }, [profiles, ready]);
  useEffect(() => { if (ready) localStorage.setItem(PROJECT_STORAGE_KEY, JSON.stringify({ schemaVersion: 1, projects: [project] })); }, [project, ready]);
  const active = profiles.find(p => p.id === project.activeProfileId) || null;
  const context = useMemo(() => buildPromptContext(project, active), [project, active]);
  const saveDraft = () => { if (!draft) return; const updated = { ...draft, name: draft.name.trim() || "Untitled profile", version: profiles.some(p => p.id === draft.id) ? draft.version + 1 : 1, updatedAt: new Date().toISOString() }; setProfiles(current => current.some(p => p.id === updated.id) ? current.map(p => p.id === updated.id ? updated : p) : [...current, updated]); setDraft(null); };
  const addSignal = () => { const value = signal.trim(); if (!value) return; setProject(p => ({ ...p, updatedAt: new Date().toISOString(), signals: [...p.signals, { id: `signal-${Date.now()}`, text: value, source: "Manual", pinned: false, rejected: false }] })); setSignal(""); };
  const generate = async () => { const response = await fetch("/api/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(context) }); const data = await response.json(); setResult({ id: data.id, influence: context.influence }); };
  if (!ready) return <main className={styles.workspace}>Restoring your workspace…</main>;
  return <main className={styles.workspace}><header><p className={styles.eyebrow}>Research Signal Workspace</p><h1>Make the work yours—on purpose.</h1><p>Project instructions win. A selected taste profile supplies reusable preferences; pinned research outranks general research. Nothing is applied invisibly.</p></header>
    <div className={styles.grid}><section className={styles.card}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>Project memory</p><h2>{project.title}</h2></div></div><label>Project name<input value={project.title} onChange={e => setProject(p => ({ ...p, title: e.target.value, updatedAt: new Date().toISOString() }))} /></label><label>Project-specific instructions <small>Highest priority—these override a profile when they conflict.</small><textarea value={project.instructions} onChange={e => setProject(p => ({ ...p, instructions: e.target.value, updatedAt: new Date().toISOString() }))} placeholder="What is unique about this project?" /></label>
      <div className={styles.sectionTitle}><div><p className={styles.eyebrow}>Research signals</p><h2>Keep only what should influence this project</h2></div></div><div className={styles.add}><input value={signal} onChange={e => setSignal(e.target.value)} onKeyDown={e => e.key === "Enter" && addSignal()} placeholder="Add a research signal" /><button onClick={addSignal}>Add</button></div>{project.signals.length === 0 ? <p className={styles.muted}>No research signals yet.</p> : <ul className={styles.signals}>{project.signals.map(s => <li key={s.id} className={s.rejected ? styles.rejected : ""}><span>{s.text}</span><button onClick={() => setProject(p => ({ ...p, signals: p.signals.map(x => x.id === s.id ? { ...x, pinned: !x.pinned } : x) }))}>{s.pinned ? "Unpin" : "Pin"}</button><button onClick={() => setProject(p => ({ ...p, signals: p.signals.map(x => x.id === s.id ? { ...x, rejected: !x.rejected } : x) }))}>{s.rejected ? "Restore" : "Reject"}</button></li>)}</ul>}</section>
      <aside className={styles.card}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>Reusable taste profiles</p><h2>{active ? active.name : "No active profile"}</h2></div><button onClick={() => setDraft(createTasteProfile())}>New</button></div><p className={styles.muted}>{active ? "This profile is explicitly applied to this project." : "Select one profile at a time to keep preference semantics clear."}</p>{profiles.length === 0 ? <p className={styles.empty}>Create a profile to reuse a visual direction, voice, constraints, and avoid rules.</p> : <ul className={styles.profiles}>{profiles.map(profile => <li key={profile.id} className={profile.id === project.activeProfileId ? styles.selected : ""}><button className={styles.profileName} onClick={() => setProject(p => ({ ...p, activeProfileId: p.activeProfileId === profile.id ? null : profile.id }))}>{profile.name}<small>{profile.id === project.activeProfileId ? "Active — click to deselect" : "Apply to project"}</small></button><button aria-label={`Edit ${profile.name}`} onClick={() => setDraft(profile)}>Edit</button><button aria-label={`Duplicate ${profile.name}`} onClick={() => setProfiles(p => [...p, createTasteProfile({ ...profile, id: undefined, name: `${profile.name} copy` })])}>Copy</button><button aria-label={`Delete ${profile.name}`} onClick={() => { setProfiles(p => p.filter(x => x.id !== profile.id)); setProject(p => p.activeProfileId === profile.id ? { ...p, activeProfileId: null } : p); }}>Delete</button></li>)}</ul>}</aside>
    </div><section className={styles.card}><p className={styles.eyebrow}>Generation context</p><h2>Transparent prompt construction</h2><p className={styles.muted}>Rejected signals are excluded. This preview is exactly the context sent to generation.</p><pre>{context.prompt || "Add project instructions, a profile, or research signals to build context."}</pre><button className={styles.generate} onClick={generate}>Generate with this context</button>{result && <p className={styles.success}>Generation {result.id} used {result.influence.profile ? `${result.influence.profile.name} (v${result.influence.profile.version})` : "no taste profile"} and {result.influence.usedSignalIds.length} accepted signal(s). Metadata is retained for reproducibility.</p>}</section>
    {draft && <div className={styles.modal} role="dialog" aria-modal="true" aria-label="Taste profile editor"><div className={styles.dialog}><h2>{profiles.some(p => p.id === draft.id) ? "Edit taste profile" : "Create taste profile"}</h2><label>Name<input autoFocus value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label>{fields.map(([key, label, placeholder]) => <label key={key}>{label}<textarea value={draft[key] as string} placeholder={placeholder} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}<div className={styles.actions}><button onClick={() => setDraft(null)}>Cancel</button><button onClick={saveDraft}>Save profile</button></div></div></div>}</main>;
}
